---
functional:
  - Пользователь должен иметь возможность опробовать простой бой без регистрации
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ зарегистрировать учетную запись
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ войти в учетную запись
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ авторизоваться с помощью Github и Discord
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ восстоновить доступ к учетную запись
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ редактировать профиль 
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ создавать,вступать в бой с другим игроком или ботом
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ устонавливать параметры создаваемой игры:уровень,тип игры,контроль времени,выбор задачи
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ наблюдать за чужими боями 
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ бросить вызов другому игроку
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ общаться с другими игроками через общий или личный чат
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ изменять язык програмирования во время боя
  - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ перезайти в игру до истечения таймера или до выполнения задачи его апонентом в случае дисконекта
  - Во время боя противники могут наблюдать за кодом оппонента
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Участник не может изменить задачу или изменить код в терминале оппонента 
  - бой закончен если вышло время, задача была решена в течении отведенного времяни или задача не была решена в течении отведенного времени 
